### ISSUE TITLE
Please help! Why can't I open the download link of dataset?

### ISSUE THREAD

**Issue by xs14331309** [vkverma01/Zero-Shot#1]

**Comment by vkverma01** [comment]
I am able to download the dataset. Please check once.
https://drive.google.com/uc?id=1M55QXL76rX3vA0E-foKuUa77O5Vn3DGY&export=download

**Comment by xs14331309** [comment]
> I am able to download the dataset. Please check once.
> https://drive.google.com/uc?id=1M55QXL76rX3vA0E-foKuUa77O5Vn3DGY&export=download

Thank you, this link works well!
